### ISSUE TITLE
BETA is too low

### ISSUE THREAD

**Issue by Wanfanel** [diogo-fernan/aco#3]
`#define BETA	(double) 0.8`
BETA should be equal or greater than 1

**Comment by diogo-fernan** [comment]
The value of `BETA` is meant to regulate the weight (or importance) given to the component of the distance between cities `ETA`. The `pow` function is used with `BETA` as exponent for the calculated distance, as seen below, which makes `ETA` respectively smaller and larger than the actual calculated distance if `0 < BETA < 1` and if `1 <= BETA`:

https://github.com/diogo-fernan/aco/blob/1544a9c5ae5ed8e8a71924af44ad7fae3f4788d1/src/ACO.cpp#L156

**Comment by Wanfanel** [comment]
I know this I'm already done my "aco" program with graphic. and beta should(maybe not must) be higher than 1 to find best solution faster, I tested on my program and saw at English wiki 

> 0 ≤ α and β ≥ 1

**Comment by diogo-fernan** [comment]
As I said, the parameter takes or gives weight to the distance between cities. The purpose is to adjust this value along with others to tune the algorithm. `0 < BETA < 1` is acceptable in this regard.

**Comment by Wanfanel** [comment]
BETA > 1 isn't acceptable? with 9 cities all connected with ALFA 0.5 BETA 0,8 my 3 ants look for best answer in 500 or more iterations, with ALFA 1.5 BETA 2.8 they founding way below 50 iterations ^_^ with fewer cities in instant ^^

distance between cities and beta don't change then you can make table is good with more iterations :-)
