### ISSUE TITLE
Final edge pheromone update in ACO::updatePHEROMONES

### ISSUE THREAD

**Issue by divanshArora** [diogo-fernan/aco#4]
In function:
`
void ACO::updatePHEROMONES () {
`
If the tour is 1->2->3->1, the above only updates pheromone for 1->2 2->3 but not for 3->1. Shouldn't that be updated too? length() function does not take into account the last edge as well.

**Comment by diogo-fernan** [comment]
Hello there,

Can you elaborate more on that? The loops at https://github.com/diogo-fernan/aco/blob/master/src/ACO.cpp#L288-L293 and https://github.com/diogo-fernan/aco/blob/master/src/ACO.cpp#L167-L169 respectively iterate through all pheromone values and edges.

**Comment by divanshArora** [comment]
Hi,

The array `ROUTE` is of length `NUMCITIES`. So for example, Say we have 3 cities and an ant found route 1->2->3 as feasible route. `ROUTE` will now be 1, 2, 3 [https://github.com/diogo-fernan/aco/blob/master/src/ACO.cpp#L167](url) will iterate over indices 0 and 1 and add edge weight for edges 1->2 and 2->3 only. But afaik, we should also take the weight of edge 3->1 in consideration. Similarly, [https://github.com/diogo-fernan/aco/blob/master/src/ACO.cpp#L281](url) will not update `DELTAPHEROMONES` for 3->1. This will be 0. What do you think?

**Comment by diogo-fernan** [comment]
As far as I remember the algorithm finds an iterative solution to the shortest path between a starting point and destination. So, in your example, 3->1 would not make sense as it is an inverse path and goes back to the origin. Please see "Computational Intelligence: An Introduction" (first edition from 2002) by Andries Engelbrecht for more information as it provides the theory for the algorithm.
